apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
spec:
  replicas: 3
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: wurstmeister/zookeeper
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 2181
            - containerPort: 2888
            - containerPort: 3888
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-srv
spec:
  type: LoadBalancer
  selector:
    app: zookeeper
  ports:
    - name: zoo1-2181
      protocol: TCP
      port: 2181
      targetPort: 2181
    - name: zoo1-2888
      protocol: TCP
      port: 2888
      targetPort: 2888
    - name: zoo1-3888
      protocol: TCP
      port: 3888
      targetPort: 3888
