apiVersion: v1
kind: ReplicationController
metadata:
  name: kafka1
spec:
  replicas: 1
  selector:
    app: kafka1
  template:
    metadata:
      name: kafka1
      labels:
        app: kafka1
    spec:
      containers:
        - name: kafka1
          image: wurstmeister/kafka
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://:9092
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://127.0.0.1:9092
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper1-srv:2181
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
            - name: KAFKA_DELETE_TOPIC_ENABLE
              value: "true"
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: kafka2
spec:
  replicas: 1
  selector:
    app: kafka2
  template:
    metadata:
      name: kafka2
      labels:
        app: kafka2
    spec:
      containers:
        - name: kafka2
          image: wurstmeister/kafka
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_BROKER_ID
              value: "2"
            - name: KAFKA_LISTENERS
              value: PLAINTEXT://:9092
            - name: KAFKA_ADVERTISED_LISTENERS
              value: PLAINTEXT://127.0.0.1:9092
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper1-srv:2181,zookeeper2-srv:2181
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
