apiVersion: v1
kind: Service
metadata:
  name: zookeeper1-srv
spec:
  selector:
    app: zookeeper1
  type: LoadBalancer
  ports:
    - name: zoo1-2181
      protocol: TCP
      port: 2181
      targetPort: 2181
    - name: zoo1-2888
      protocol: TCP
      port: 2888
      targetPort: 2888
    - name: zoo1-3888
      protocol: TCP
      port: 3888
      targetPort: 3888
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper2-srv
spec:
  selector:
    app: zookeeper2
  type: LoadBalancer
  ports:
    - name: zoo2-2181
      protocol: TCP
      port: 2181
      targetPort: 2181
    - name: zoo2-2888
      protocol: TCP
      port: 2888
      targetPort: 2888
    - name: zoo2-3888
      protocol: TCP
      port: 3888
      targetPort: 3888
